### ISSUE TITLE
question: sandboxed builds

### ISSUE THREAD

**Issue by Karitham** [Cloudef/zig2nix#11]
Hello, I've been trying to package a [super-html](https://github.com/Karitham/super-html/blob/nix/flake.nix) and noticed zig2nix doesn't produce sandboxed builds.

Would it be possible to achieve? Eg by replacing the zig pulling code with `fetch*`?

I'm not sure how feasible it would be, nor if it's worth it.

Or am I perhaps doing something wrong in packaging that application?

**Comment by Cloudef** [comment]
zig2nix should be able to do full sandboxed builds as long as your project has zon2json-lock file.
