### ISSUE TITLE
Binding Wayland

### ISSUE THREAD

**Issue by ethanthoma** [Cloudef/zig2nix#15]
Hello,

I am trying to use the wayland-client headers and libraries in my zig project. I tried to include wayland vai the `enableWayland = true;` flag but the zig builder still fails to find it when running `nix build`. I also tried setting `LD_LIBRARY_PATH`, `LIBRARY_PATH`, `NIX_LDFLAGS`, and `NIX_CFLAGS_COMPILE` manually in the `packages.target` but the zig builder still cannot find it as I assumed it would from [NativePaths.detect](https://ziglang.org/documentation/master/std/#std.zig.system.NativePaths.detect).

My build.zig is really simple for this and only has:
```ts
exe.linkLibC();
exe.linkSystemLibrary("wayland-client");
```

Thanks and let me know what other information to provide!

**Comment by Cloudef** [comment]
You need to add `pkg-config` to `nativeBuildInputs`.

**Comment by Cloudef** [comment]
also pushed https://github.com/Cloudef/zig2nix/commit/3e4b85f9a711b3b618db90562b1d9366d2b97091 which should work even without adding pkg-config to nativeBuildInputs.

**Comment by ethanthoma** [comment]
> You need to add `pkg-config` to `nativeBuildInputs`.

I added it to the env:
```nix
        env = zig2nix.outputs.zig-env.${system} {
                enableVulkan = true;
                enableWayland = true;
                customRuntimeDeps = with env.pkgs; [ pkg-config ];
        };
```

and to the package build:
```nix
      packages.target = genAttrs allTargetTriples (target: env.packageForTarget target ({
        src = cleanSource ./.;
                    
        nativeBuildInputs = with env.pkgs; [pkg-config];

        preBuild = ''
            mkdir -p /build/source/wgpu_native
            cp ${wgpu-native.out}/lib/* /build/source/wgpu_native
        '';

        zigPreferMusl = true;
        zigDisableWrap = true;
      } // optionalAttrs (!pathExists ./build.zig.zon) {
        pname = "my-zig-project";
        version = "0.0.0";
      }));
```

However it still fails. I also updated my flake to latest. Is there something else I am missing or have to set via zig? My searched paths for the adding the system library is none for some reason:
```
install
+- install default
   +- zig build-exe default ReleaseSafe x86_64-linux-gnu failure
error: error: unable to find dynamic system library 'wayland-client' using strategy 'paths_first'. searched paths: none
```

**Comment by ethanthoma** [comment]
Do I need to set any environment variables myself? I imagined that setting enableWayland would link it for me but I am not too sure

**Comment by Cloudef** [comment]
Seems like you have to also put the wayland deps into `buildInputs` they aren't derived from the runtime meant for non `nix build`.

**Comment by ethanthoma** [comment]
Awesome, got everything to work. Thanks so much
